### ISSUE TITLE
"Also apply filter to matching messages." Option

### ISSUE THREAD

**Issue by Kilbourne** [mbrt/gmailctl#159] opened 2020-12-28 19:40 UTC
On gmail , there's an option to apply the current filter update to old messages. Any way to achieve the same with gmailctl=?

**Comment by mbrt** [comment] 2020-12-29 14:41
Duplicate of #113.

This is a known and unsupported use case. Added a note in the README in 6a866a525de8fbe97de5429790880ef99ba6c35c.

**Closed by mbrt** 2020-12-29 14:41 UTC
